### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jasonherndon** [maddhatter/laravel-fullcalendar#1]
Awesome package - exactly what I was looking for in terms of integration of the fullcalendar library into Laravel. Are you putting together documentation for this? Packagist has the require bit but I'm not sure about other usage. Looking through all the classes now to get an idea but docs would be most helpful. :+1: for the package though!

**Comment by maddhatter** [comment]
Finally had some time to write up some documentation. Hope it's clear...

**Comment by jasonherndon** [comment]
Awesome - thanks, that makes using this so much clearer!
