### ISSUE TITLE
Can't seem to display the calendar

### ISSUE THREAD

**Issue by CedricBongaerts** [maddhatter/laravel-fullcalendar#10]
I'm quite new to Laravel so I might be doing this all wrong, but I can't seem to get the calendar displayed. I keep getting the error 'Undefined variable: calendar (View: /home/vagrant/Code/Laravel/resources/views/pages/calendar.blade.php)'

I made a stackoverflow question with all the code here: 
http://stackoverflow.com/questions/30662238/cannot-get-fullcalendar-to-work-laravel-5

Mind helping me out?
Thanks,
Cedric

**Comment by CedricBongaerts** [comment]
I've held this aside for a bit to work on other stuff in my project but it's time for me to configure the calendar. At the moment, the calendar show the sample view posted on the ReadMe. But if I wish to use the calendar on fullcalendar.io, do I need to implement the jquery?
I dont seem to have the buttons through the header even though when I browse to the Calendar.php it contains the code:

protected $defaultOptions = [
        'header' => [
            'left' => 'prev,next today',
            'center' => 'title',
            'right' => 'month,agendaWeek,agendaDay',
        ],
        'eventLimit' => true,
    ];

Is there a reason why it's not showing the buttons in the header?

Also, for some reason it only shows the first Event that I make in the database.
Sorry for the many questions but I've been googling this and haven't found any answers.

Thanks,
Ced

**Comment by maddhatter** [comment]
Make sure your print css file has the `media="print"` attribute:

```html
<link rel="stylesheet" media="print" href="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/fullcalendar.print.css"/>
```
Looks like tha'ts missing from the sample view in the documentation, I'll update that

**Comment by Conquerer** [comment]
$events = [];
        $data = Event::all();
        if($data->count()) {
            foreach ($data as $key => $value) {
                $events[] = Calendar::event(
                    $value->place,
                    true,
                    new \DateTime($value->start_date),
                    new \DateTime($value->end_date.' +1 day'),
                    null,
                    // Add color and link on event
                  [
                      'color' => '#f05050',
                      'url' => 'pass here url and any route',
                  ]
                );
            }
        }
        $calendar = Calendar::addEvents($events);
        return view('admin.calender', compact('calendar'));

This is my function in the controller and  I dis use Calendar in the controller set its aliases and providers as well but the calendar is not visible
please help me

**Comment by AliVeseli** [comment]
$db_events = Event::get();
        $events = [];
        foreach ($db_events as $event) {
            $events[] = \Calendar::event(
                $event->place,
                true,
                new \DateTime($value->start_date),
                new \DateTime($value->end_date.' +1 day'),
                0,
                [
	                'color' => '#f05050',
	                'url' => 'pass here url and any route',
                ]
            );
        }
        
        $calendar = \Calendar::addEvents($events);
        return view('admin.calender', compact('calendar'));

**Comment by AliVeseli** [comment]
If Calendar does not appear at all check the View check the script ordering 

it should be 
  <link href="{{ asset('vendor/fullcalendar/fullcalendar.min.css') }}" rel="stylesheet">
    {!! $calendar->calendar() !!}
 <script src="{{ asset('vendor/jquery/jquery-3.2.1.min.js') }}"></script>
<script src="{{ asset('js/moment.js') }}"></script>
<script src="{{ asset('vendor/fullcalendar/fullcalendar.min.js') }}"></script>
 {!! $calendar->script() !!}

**Comment by Conquerer** [comment]
Thanks AliVeseli...,For your kind help but,the same issue repeats again..I can't able to visualize where is the error.I had added all the css and js files required but...
![view page](https://user-images.githubusercontent.com/18400955/48980772-6f4f7e80-f0f3-11e8-847f-37e34da7d958.JPG)

![my_controller](https://user-images.githubusercontent.com/18400955/48980732-fa7c4480-f0f2-11e8-8fe7-84d6adbc1213.JPG)
![my_view_page](https://user-images.githubusercontent.com/18400955/48980733-fa7c4480-f0f2-11e8-861f-acee31b2733d.JPG)

**Comment by AliVeseli** [comment]
You have jquerry inserted twice remove it one .

**Comment by AliVeseli** [comment]
Remove version 1.11.2 keep the 2.1.3

**Comment by Conquerer** [comment]
Updated as said but same issue i.e  blank ,Admin or anyone, AliVeseli can you help me to know the error so that I can rectify it..

**Comment by essineden** [comment]
Seems like I'm having the same issue - i think. 

I've followed the youtube video and the instructions from the website but I'm getting 

> Undefined variable: calendar_details (View: C:\xampp\htdocs\...\resources\views\pages\event.blade.php)

Am I missing something from the instructions? The Add Event is working but after adding 

{!! $calendar_details->calendar() !!}

The application doesn't seem to work anymore. 

TIA
