### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by iamgp** [maddhatter/laravel-fullcalendar#11]
The model (*not* the interface, as you say) should extend the Eloquent\Model, rather than just Eloquent.

e.g.

```php
namespace App;

use Illuminate\Database\Eloquent\Model;

class EventModel extends Model implements \MaddHatter\LaravelFullcalendar\IdentifiableEvent
{
}
```

**Comment by maddhatter** [comment]
I'd say it's inconsequential since it's just demo code. If it really bugs you create a pull request.

**Comment by maddhatter** [comment]
And I can't find any misuse of  "Interface" vs "Model". Do you have a specific example?
