### ISSUE TITLE
"Type error: Argument 1 passed to MaddHatter\LaravelFullcalendar\EventCollection::push() must implement interface MaddHatter\LaravelFullcalendar\Event, null give

### ISSUE THREAD

**Issue by rishabhgoel9797** [maddhatter/laravel-fullcalendar#110]
Below is my controller. Please tell

`<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Calendar;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Auth;
use App\Events;
use Illuminate\Support\Facades\Redirect;
class calendarController extends Controller
{
    //
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $events=Events::get();
        $event_list=[];
        foreach($events as $key => $event)
        {
            $event_list = Calendar::event(
                $event->event_title,
                true,
                new \DateTime($event->event_date),
                new \DateTime($event->event_date.' +1 day')
            );
        }
        $calendar_details = Calendar::addEvents($event_list);
        return view('dashboard.calendar',compact('calendar_details'));

    	//return view('dashboard.calendar');
    }
    public function addEvent(Request $request)
    {
        $data = $request->all();

        $validator=Validator::make($request->all(),[
            'event_title'=>'required',
            'event_date'=>'required'
        ]);

        if($validator->fails())
        {
            \Session::flash('warning','Please enter the valid details');
            return Redirect::to('/calendar')->withInput()->withErrors($validator);
        }

        Events::create([
            'event_title' => $data['event_title'],
            'event_date' => $data['event_date'],
        ]);

        $event=new Events;
        $event->event_title=$request['event_title'];
        $event->event_date=$request['event_date'];
        $event->save();

        \Session::flash('success','Event successfully added');
        return Redirect::to('/calendar');
    }
}
`

**Comment by Pablo-Araya** [comment]
foreach($events as $key => $event)
    {
        $event_list = Calendar::event(                  **// should be:     $event_list[] = Calendar::event(**
            $event->event_title,
            true,
            new \DateTime($event->event_date),
            new \DateTime($event->event_date.' +1 day')
        );
    }

**Comment by rishabhgoel9797** [comment]
Yes, it worked thank you.I am closing this case
