### ISSUE TITLE
Laravel 5.7 using Bootstrap 4 - Header navigation buttons not appearing

### ISSUE THREAD

**Issue by Dmarthaller** [maddhatter/laravel-fullcalendar#129]
I have successfully used this package in the past with a laravel 5.5 on a Bootstrap 3 theme.

I have the calendar rendering but all I see on the header is the Month and Year, missing is the left hand navigation arrow buttons and the right hand change view buttons.  The fullcalendar.io library version I installed in V3.9.0.

Is there a step that I have missed to turn on the view options?

**Comment by Dmarthaller** [comment]
Oh, I just solved my problem. 

On the css for printing I was missing the media="print" statement.

 <link href="{{ asset('css/fullcalendar.print.min.css') }}" rel="stylesheet" media="print">

**Comment by Malkom** [comment]
@Dmarthaller Can you explain your solution ? I have the same problem.

**Comment by Dmarthaller** [comment]
Hi @Malkom this was a long time ago so I don't remember the specific issue. When I pulled up my code in change control I see that I made the following changes to the Blade file containing the calendar.

```
@push('css')
    <link href="{{ asset('css/fullcalendar.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/fullcalendar.print.min.css') }}" rel="stylesheet" media="print">
@endpush

@push('scripts')
    <script src="{{ asset('js/moment.min.js') }}"></script>
    <script src="{{ asset('js/fullcalendar.min.js') }}"></script>
@endpush
```

I also made a note that I needed to add the media="print" phrase to the stylesheet code above. I hope that this helps you in some way.

**Comment by Malkom** [comment]
Of course, it's help ;)

Thank you 👍
