### ISSUE TITLE
i want to add variable into the script file "script.blade.php"

### ISSUE THREAD

**Issue by serhan** [maddhatter/laravel-fullcalendar#14]
as var cal = $('#calendar-{{ $id }}').fullCalendar({{ $options }});
because if i want to render event into the select function i received error "$(...).fullCalendar is not a function"

**Comment by maddhatter** [comment]
Did you include the http://fullcalendar.io/ files in your HTML somewhere?
This package doesn't include them, you need to see their site to set up the
client-side code

--
Shawn Tunney
