### ISSUE TITLE
Non-static method

### ISSUE THREAD

**Issue by xitude** [maddhatter/laravel-fullcalendar#15]
Using Laravel 5,
Getting this issue when trying to follow the docs.

Non-static method MaddHatter\LaravelFullcalendar\Calendar::addEvents() should not be called statically, assuming $this from incompatible context

**Comment by maddhatter** [comment]
You need to use the facade class in order to do calls like that. If you
created an alias in app.php, try calling `addEvents()` on `\Calendar`
instead of `MaddHatter\LaravelFullcalendar\Calendar`

--
Shawn Tunney
