### ISSUE TITLE
Failed to be installed on Laravel 6.2

### ISSUE THREAD

**Issue by kalideir** [maddhatter/laravel-fullcalendar#158]
I have been trying on installing this package for my new project using the command:
composer require maddhatter/laravel-fullcalendar
but I am getting this error:
Your requirements could not be resolved to an installable set of packages.

Any ideas to resolve the issue would be appreciated.

**Comment by ShapesGraphicStudio** [comment]
Hi,
Same issue with Laravel 6.8, did you get this solved ?

**Comment by kalideir** [comment]
Unfortunately have not!. However it seems an issue with versions, try to downgrade Laravel's version.

**Comment by ShapesGraphicStudio** [comment]
OK, thank you, yes indeed it's a version issue.
As I do not want to downgrade Laravel, I will go with the npm package.
Too bad though, as this is a nice package, and there's a pull request with Laravel 6.0 available..

**Comment by progcode** [comment]
You can use this fork with Laravel6+ https://packagist.org/packages/progcode/laravel-fullcalendar#v1.3.2
