### ISSUE TITLE
how to add addEvent with custom array 

### ISSUE THREAD

**Issue by mean-cj** [maddhatter/laravel-fullcalendar#17]
Hello

Your method  "Calendar::addEvent" can be use only eloquent

Please Suggesting how to add custom array
```php
          -> addEvent( [
                'title' => $event->title, //event title
                'allDay'  => true,
                'start' => $event->startTime,
                'end'  => $event->endTime,
                'id' => $event->id,
                'color' => 'red'
            ]);
```

When I use with mongodb "Calendar::addEvent" method is not support MongoDate
Error is
```
FatalErrorException in EventCollection.php line 39:
Call to undefined method MongoDate::format()
```

the "Calendar::event" method is not support custom attribute
```php
public static function event($title, $isAllDay, $start, $end)
```

thank you so much.
cj.

**Comment by maddhatter** [comment]
Does the event you're trying to pass implement `MaddHatter\LaravelFullcalendar\Event` ? 

The `getStart()` and `getEnd()` methods need to return a DateTime (or [Carbon](http://carbon.nesbot.com/)) object.

**Comment by maddhatter** [comment]
My previous comment to this makes no sense... but [v1.2.4](https://github.com/maddhatter/laravel-fullcalendar/releases/tag/v1.2.4) let's you pass an array of custom attributes.
