### ISSUE TITLE
Missing passing id in constructor.

### ISSUE THREAD

**Issue by krowinski** [maddhatter/laravel-fullcalendar#18]
Example 

>$event = \Calendar::event(
>    "Valentine's Day", //event title
>    true, //full day event?
>    '2015-02-14', //start time, must be a DateTime object or valid DateTime format >(http://bit.ly/1z7QWbg)
>    '2015-02-14' //end time, must be a DateTime object or valid DateTime format 
>(http://bit.ly/1z7QWbg),
>    1 //optional event ID
>);

But LaravelFullcalendar/Calendar.php dont have support id

 >   public static function event($title, $isAllDay, $start, $end)
  >  {
   >     return new SimpleEvent($title, $isAllDay, $start, $end);
   > }

but SimpleEvent is supporting

>    public function __construct($title, $isAllDay, $start, $end, $id = null)

**Comment by maddhatter** [comment]
Fixed by #21 

If you need this on the 4.0 branch, reopen and I'll address
