### ISSUE TITLE
Laravel 5 Update

### ISSUE THREAD

**Issue by jasonherndon** [maddhatter/laravel-fullcalendar#2]
Thanks @maddhatter for the updates to this - I ran it on 4.2 and its very clean. I'm moving over my project to Laravel 5 next month - any plans to update this for L5 or tips on how I might do that? Thanks again!

**Comment by maddhatter** [comment]
I'm planning on moving over the project I'm using this in to L5 in the next month or so and will be updating this at the same time (or sooner).

**Comment by jasonherndon** [comment]
Awesome - thanks again!

**Comment by maddhatter** [comment]
Since I just dug thru all of it to write up the documentation, I figured I might as well make the L5 changes while it was fresh.

The 0.1.* versions will be Laravel 4.2 and the 1.*.* will be Laravel 5
