### ISSUE TITLE
Add event on click on calendar not working

### ISSUE THREAD

**Issue by maheshkharote** [maddhatter/laravel-fullcalendar#20]
Hi,
Does the full calendar require a table? I was getting error so I created a table named 'event_models'.
Is it correct way or there is a another way round.
The calendar started working then. Now, the calendar shows those events that are written in the controller. What should I do if I have to add a new event to calendar that will be saved to database and showed on the calendar. How can I get the added event into a json so that I can store it. 
I am doing this in laravel 5, I have just started using it.

**Comment by nezaboravi** [comment]
You can create ajax call by clicking on Calendar field. 
Calendar::addEvents($events, $customOptions)->setCallbacks([ //set fullcalendar callback options (will not be JSON encoded)
			// 'event' => 'function() {alert("Callbacks!");}'
// here you can do you $ajax.post....
// fullcalndear method is 'eventClick' . When you click on field in full calndear view, you can open a form, save your event in db etc...
			'eventClick' => "function(calEvent, jsEvent, view) {

			alert('Event: ' + calEvent.start);
			alert('Coordinates: ' + jsEvent.pageX + ',' + jsEvent.pageY);
			alert('View: ' + calEvent.id);

			// change the border color just for fun
			$(this).css('border-color', 'red');

		}"
		])

**Comment by maddhatter** [comment]
Little late... but better than never replying...

You can create an Eloquent model (and corresponding database table) to store your events, and then have it implement the `MaddHatter\LaravelFullcalendar\Event` interface. You can probably find tutorials online to create the model and how to handle basic CRUD operations

**Comment by viniciusalonso** [comment]
Hi, 
exists any way of  put in callbacks events in javascript files ?
