### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by johnarc5** [maddhatter/laravel-fullcalendar#22]
Argument 1 passed to MaddHatter\LaravelFullcalendar\Calendar::addEvent() must implement interface MaddHatter\LaravelFullcalendar\Event, null given,

**Comment by maddhatter** [comment]
What did you pass to addEvent? Was it `null`?

**Comment by johnarc5** [comment]
I have solved it by my own.. thanks by the way maddhatter,.. ;)

**Comment by johnarc5** [comment]
I have one other query..
can we add events by using javascript or jquery using your package? and if yes then how?

**Comment by maddhatter** [comment]
You should be able to add events with the FullCalendar js code. [This StackOverflow question](http://stackoverflow.com/questions/10016936/in-jquery-fullcalendar-can-i-add-a-new-event-without-refreshing-the-whole-month) looks like it should be able to help.

**Comment by shahilnissam** [comment]
I have the same issue.. please help..
Argument 1 passed to MaddHatter\LaravelFullcalendar\Calendar::addEvent() must implement interface MaddHatter\LaravelFullcalendar\Event, null given,

Error is in : CalendarController.php

// This is my controller test code..

    $events[] = \Calendar::event(
            'Event One', //event title
            false, //full day event?
            '2015-06-05T0800', //start time (you can also use Carbon instead of DateTime)
            '2015-06-05T0800', //end time (you can also use Carbon instead of DateTime)
            0 //optionally, you can specify an event ID
        );

        $eloquentEvent = EventModel::first(); //EventModel implements MaddHatter\LaravelFullcalendar\Event

        $calendar = \Calendar::addEvents($events) //add an array with addEvents
        ->addEvent($eloquentEvent, [ //set custom color fo this event
            'color' => '#800',
        ])->setOptions([ //set fullcalendar options
            'firstDay' => 1
        ])->setCallbacks([ //set fullcalendar callback options (will not be JSON encoded)
            'viewRender' => 'function() {alert("Callbacks!");}'
        ]);

        return view('test', compact('calendar'));

**Comment by maddhatter** [comment]
Did you create an `EventModel` class? That sample code is just to show how to use an existing Eloquent model with the class
