### ISSUE TITLE
UI 

### ISSUE THREAD

**Issue by mitacliff** [maddhatter/laravel-fullcalendar#23]
am trying to change the font color, what option should i pass

**Comment by maddhatter** [comment]
The font color is more of a Full-Calendar.io issue, not with this PHP backend helper.

This might help: http://fullcalendar.io/docs/event_rendering/Colors/

**Comment by wdog** [comment]
suppose you have a model called Event and contains the field textcolor and color
you can do something like this

```
  $events_db = $modelEvent->all();
    foreach ($events_db as $e) {
      $calendar = Calendar::addEvent($e, ['color' => $e->color, 'textColor' => $e->textcolor]);
    }
```
