### ISSUE TITLE
how to pass "url" to event method

### ISSUE THREAD

**Issue by vladvisinescu** [maddhatter/laravel-fullcalendar#25]
... or to addEvent.

I`ve tried this

```php
    $calendar = \Calendar::addEvent([
	 'title'  => $task->patient), 
	 'allDay' => false, 
	 'start'  => $task->from_date, 
	 'end'    => $task->to_date, 
	 'url'    => route( 'dashboard.task.show', $task->id )
    ]);
```

but it doesn`t work. Am I missing something ?

**Comment by ArtbyArjan** [comment]
How did you solve this? I'm running into the same problem.

**Comment by vladvisinescu** [comment]
I solved this but ended up not using this package anymore actually. I`m now just retrieving events through fullcalendar`s "events" blablabla.
While I was searching through the code to post my solution I`ve seen your other thread and the better solution you got there so... good luck :) !
