### ISSUE TITLE
How to pass 'url' to events when using addEvents

### ISSUE THREAD

**Issue by ArtbyArjan** [maddhatter/laravel-fullcalendar#26]
First of all, thanks for this package. Works really nice, but I'm running into a problem which I can't figure out.

I'm adding events to a calendar as an array. There are three types of events:
- events where a user has been invited to
- events where the user has accepted the invite
- events where the organizer has approved the accepted invitation

Here's the code in my controller:
```php
 public function getCalendar()
    {
        $user = Auth::user();
        // get the projects to which the user has been invited
        $projects = ProjectUser::where('user_id', $user->id )->get();
        $invited_events = [];
        $accepted_events = [];
        $approved_events = [];

        foreach( $projects as $event )
        {
            // only get the events where the admin_status hasn't been set yet
            if( !isset($event->admin_status_id) ){
                switch( $event->status_id ){
                    // invite has been sent to the freelancer, but hasn't been accepted
                    case 1:
                    array_push( $invited_events, \Calendar::event( 
                        $event->project->name, 
                        false, 
                        $event->project->date_event_from, 
                        $event->project->date_event_till, 
                        $event->project->id
                        ) 
                    );
                    break;
                    // invite has been accepted by the freelancer
                    case 2:
                    array_push( $accepted_events, \Calendar::event( 
                        $event->project->name, 
                        false, 
                        $event->project->date_event_from, 
                        $event->project->date_event_till, 
                        $event->project->id
                        ) 
                    );
                    break;
                } 
            } elseif( $event->admin_status_id === 1 ){
                // freelancer has been approved by brok decor
                array_push( $approved_events, \Calendar::event( 
                    $event->project->name, 
                    false, 
                    $event->project->date_event_from, 
                    $event->project->date_event_till, 
                    $event->project->id
                    ) 
                );
            }
        }

        $calendar = \Calendar::addEvents(
            $invited_events, [ 'color' => '#a0d3e8' ]
        )->addEvents(        
            $accepted_events, [ 'color' => '#f08a24' ]
        )->addEvents(
            $approved_events, [ 'color' => '#43ac6a' ]
        )->setOptions([ 
            'firstDay'          => 1, // set Monday as first day of the week
            'timeFormat'        => 'H:mm',
            'axisFormat'        => 'H:mm'
        ]); 

        return view('extranet.calendar')->with([
            'calendar' => $calendar
        ]);
    }
```
What I want to do, is make the event clickable in the calendar, so the user is directed to the detailpage of the event (with all information about that event).
The url should be '/extranet/projects/{id}'.
I have tried adding an extra property to `Calendar::event()` which didn't work (obviously, because it's not a method of `MaddHatter\LaravelFullcalendar\Event`)
I have tried adding `url` as property, the same way as `color` is added in `addEvents`, but that didn't work either because I don't know how to get the ID of the event from the `$invited_events`,`$accepted_events` or `$approved_events`.

Help?

**Comment by maddhatter** [comment]
Hmm, I get what your issue is...

Would adding an additional parameter to `Calendar::event()` that accepts an array of `key => value` pairs (so you could do something like `url => route(...)`) work? That way it can be more flexible.

Are you using the Laravel 4 or 5 branch?

**Comment by ArtbyArjan** [comment]
Sorry for the late reply. I had a day off yesterday :)

Adding an array would be a perfect solution and it could work for more properties then just `url`.

We're using the Laravel 5 branch.

**Comment by maddhatter** [comment]
I had actually implemented this awhile ago while hacking away one night, and totally forgot to commit/publish it... just tagged [v1.2.4](https://github.com/maddhatter/laravel-fullcalendar/releases/tag/v1.2.4)

Readme has [more details](https://github.com/maddhatter/laravel-fullcalendar#additional-event-parameters), but you can basically pass an array to `Calendar::event()` as the 6th parameter with `'url' => 'some url'` (you could implement the colors there as well)

**Comment by ArtbyArjan** [comment]
Awesome! Thank you!

Just updated and implemented this and it works like a charm!
