### ISSUE TITLE
draggable event

### ISSUE THREAD

**Issue by mohammad6006** [maddhatter/laravel-fullcalendar#27]
how to add draggable event like this : http://fullcalendar.io/js/fullcalendar-2.4.0/demos/external-dragging.html

**Comment by maddhatter** [comment]
I think this is probably outside of the original scope of this package. You could use the package to render the base calendar, but would need custom JS/backend code to implement the draggable events.

If you want to add something to help with creating the draggable stuff, feel free to implement and create a PR though; might be a cool thing to add.

**Comment by roulendz** [comment]
[](http://www.jqueryajaxphp.com/fullcalendar-crud-with-jquery-and-php/)

Here is good tutorial for php, but it would be good if someone rewrites it to [L5.2] 

Hope it helps someone!
