### ISSUE TITLE
script editing

### ISSUE THREAD

**Issue by alex-vele** [maddhatter/laravel-fullcalendar#3]
Hi!
I'm a bit new to this and I just cant figure out how to edit the script file ({!! $calendar->script() !!}) you set in the view so i can use the custom options from fullcalendar.io ? I would appreciate the help.

**Comment by maddhatter** [comment]
See [v0.2.0](https://github.com/maddhatter/laravel-fullcalendar/releases/tag/v0.2.0) for Laravel 4.2 or [v1.1.0](https://github.com/maddhatter/laravel-fullcalendar/releases/tag/v1.1.0) for Laravel 5
