### ISSUE TITLE
Change Lang

### ISSUE THREAD

**Issue by Luismij** [maddhatter/laravel-fullcalendar#32]
i need change the language of te calendar to 'es'
 by default, i pasted this in Calendar.php
and didn't work

protected $defaultOptions = [
        'header' => [
            'left' => 'prev,next today',
            'center' => 'title',
            'right' => 'month,agendaWeek,agendaDay',
        ],
        'eventLimit' => true,
        'lang' => 'es'
    ];

**Comment by Gummibeer** [comment]
Do you have included the language javascript file? Without there are no strings for translations.

**Comment by maddhatter** [comment]
Like Gummibeer said, you need to include an extra JS file. This page has pretty straight forward steps: http://fullcalendar.io/docs/text/lang/

**Comment by Luismij** [comment]
Thanks! it worked

**Comment by bskscmn** [comment]
Hello, 
How can I change the language acording to a selectbox from my blade page?

**Comment by Gummibeer** [comment]
@bskscmn You need to adjust the value passed from the backend by this value or use javascript to save it in localstorage and call the configuration for the fullcalendar javascript lib. https://fullcalendar.io/docs/

**Comment by fabriciodcm** [comment]
Did you add the entire fullcalendar project using npm or just the language.js ?Sorry guys I just started with laravel.  Thank you

**Comment by LuismiLabs** [comment]
@fabriciodcm  I just use the language.js in the args of the calendar.

**Comment by fabriciodcm** [comment]
@Luismij Thank you for your answer . I tried another simpler way for beginners like me. Its not correct but it worked. I inserted directly in the view like this:
<script src="//cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.2.7/lang-all.js"></script>
        <script>
            $(document).ready(function() {
                $('#calendar').fullCalendar({
                lang: 'pt-br'
                });
            });
        </script>
