### ISSUE TITLE
laravel 5.1 or 5.2

### ISSUE THREAD

**Issue by Rezakhaan** [maddhatter/laravel-fullcalendar#37]
does this package work on laravel 5.1 or 5.2?

**Comment by maddhatter** [comment]
It definitely works on 5.1 - I've not tried it on 5.2.

If you try it and find out either way, let me know?

**Comment by roulendz** [comment]
I installed on 5.2 and for me what is in reedme file works prerfect!

**Comment by maddhatter** [comment]
Awesome, thanks!
