### ISSUE TITLE
How to get to calendar ID '#calendar-VxnJa0Rz'

### ISSUE THREAD

**Issue by roulendz** [maddhatter/laravel-fullcalendar#41]
I can not figure how to thatget 

```
'#calendar-VxnJa0Rz'
```

Last part of calendar it all the time generates automatically

```
$('#calendar-??????').fullCalendar('updateEvent',event);
```

**Comment by maddhatter** [comment]
You have two options, either you can tell it what to make the ID, or you can get the randomly generated one:

```php
//option 1
$calendar->setId('my-calendar');

//option 2
$calendar->getId(); //this'll either return either 'calendar-<8 random chars>' or whatever you set it to
```

**Comment by roulendz** [comment]
Thanks,
Stupid question, but
how I can target calendar  with that random id from js or jQuery?

**Comment by simionchis** [comment]
```js
$('#calendar-{{ $calendar->getId() }}').fullCalendar('updateEvent',event);
```

**Comment by rafig256** [comment]
thank. It was also helpful to me.
but I used fullCalendar in this way:
`$('#calendar-{{$calendar->getId()}}').fullCalendar({
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay,listWeek'
                },
                isJalaali : true,
                navLinks: false,
                editable: false,
                eventLimit: true, 
                isRTL : true,
                lang : "fa",
            });`
How should I update the event now?
