### ISSUE TITLE
Laravel 5.2 - Event ID returns null

### ISSUE THREAD

**Issue by bfblackjack** [maddhatter/laravel-fullcalendar#44]
I'm using draggable events - they get inserted to my DB just fine with an auto-incremented ID. Even after refreshing the page, the calendar pulls in the event(s) but none of my events have an ID - they are all "null."

**Comment by maddhatter** [comment]
Are you extending `IdentifiableEvent`? (https://github.com/maddhatter/laravel-fullcalendar#identifiableevent-interface)

Or if you're using `Calendar::event()` to create events, are you passing the `$id` parameter?

**Comment by bfblackjack** [comment]
Ah hah - I was extending Event rather than IdentifiableEvent. Thanks!
