### ISSUE TITLE
Argument 1 passed to MaddHatter\LaravelFullcalendar\Calendar::addEvent()

### ISSUE THREAD

**Issue by koffielyder** [maddhatter/laravel-fullcalendar#45]
I am getting this error

_ErrorException in Calendar.php line 142:
Argument 1 passed to MaddHatter\LaravelFullcalendar\Calendar::addEvent() must implement interface MaddHatter\LaravelFullcalendar\Event, null given, called in C:\wamp\www\musicCentral\app\Http\Controllers\AgendaController.php on line 69 and defined_

I have used the example code
How can I fix this?

**Comment by maddhatter** [comment]
At the risk of stating the obvious... are you sure you're not passing `null` to the function? Try dumping the variable you're using before calling `addEvent`

**Comment by koffielyder** [comment]
Before I pass it it is not NULL but when it gets to the function it is null somehow

**Comment by maddhatter** [comment]
Can you share your code? http://laravel.io/bin

**Comment by koffielyder** [comment]
http://laravel.io/bin/d9M93

Here is the code of my controller the rest of the code is the same as the template

**Comment by maddhatter** [comment]
What do you get when you dump `$eloquentEvent`

**Comment by koffielyder** [comment]
Ah I get NULL there

**Comment by koffielyder** [comment]
```
$calendar = \Calendar::addEvents($events);

return view('venue.agenda.test', compact('calendar'));
```

Got it working now without the eloguentEvent

**Comment by maddhatter** [comment]
Sounds good

**Comment by koffielyder** [comment]
thanks for the help
