### ISSUE TITLE
Issue after fresh install

### ISSUE THREAD

**Issue by Movian** [maddhatter/laravel-fullcalendar#46]
Hey,

just did a fresh composer install of laravel-fullcalendar and followed instructions for installation.

Then i copied the sample code for the view and controller and I am getting the following error

Fatal error: Class 'App\Http\Controllers\EventModel' not found 

I tried adding use at the top to ensure it was looking for the right class

use MaddHatter\LaravelFullcalendar\Calendar;

we also have a header.php that gets included and I placed the links to the fullcalendar files in there so they are included.

any thoughts on what I have done wrong ?

Thanks

**Comment by maddhatter** [comment]
`EventModel` in the example is an Elequent model that implements `\MaddHatter\LaravelFullcalendar\Event` (you can see the example code for that model [here](https://github.com/maddhatter/laravel-fullcalendar#implementing-event-interface).

**Comment by Movian** [comment]
Thank you,

still new to Laravel...  added that to my controller and have some new issues with Eloquent, trying to trouble shoot those now.

Thanks again :)

**Comment by feixuedaxia** [comment]
same problems, could you help to solve it?

**Comment by dodacvan** [comment]
what folder contain EventModel. thanks
