### ISSUE TITLE
Google calendar integration

### ISSUE THREAD

**Issue by samueldervis** [maddhatter/laravel-fullcalendar#48]
I can see that full calendar supports integration for Google Calendar at http://fullcalendar.io/docs/google_calendar/ . Yet cannot find such integration in this package.

**Comment by joaoguilhermels** [comment]
Yes. To use Google Calendar you'll have to change Calendar.php and include a protected googleCalendarApiKey variable with the proper getter and setter and then change the getOptionsJson function to include the new variable when it returns the json encoded options.

**Comment by maddhatter** [comment]
Don't think that use case lends itself to this helper package.
