### ISSUE TITLE
$calendar->script() error

### ISSUE THREAD

**Issue by christophevond** [maddhatter/laravel-fullcalendar#5]
After updating the package for Laravel 4.2 I have started to receive an error message with the following: 

Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_ERROR)  Symfony\Component\Debug\Exception\FatalErrorException thrown with message "Method Illuminate\View\View::__toString() must not throw an exception" Stacktrace: #1 Symfony\Component\Debug\Exception\FatalErrorException in **editted**/app/controllers/CalController.php:0 #0 Illuminate\Exception\Handler:handleShutdown in <#unknown>:0
Method Illuminate\View\View::__toString() must not throw an exception

I have a very basic implementation without changing the default options or using any callbacks.

**Comment by maddhatter** [comment]
Sorry for the suuuuuuper slow feedback on this...

Are you still having this issue?

**Comment by christophevond** [comment]
Thank you for getting back to me. I actually ended up migrating my project to Laravel 5 and using that branch of FullCalendar. In general, you have a great plugin here!
