### ISSUE TITLE
Multiple Calendars on One Page

### ISSUE THREAD

**Issue by bfblackjack** [maddhatter/laravel-fullcalendar#50]
Displaying one calendar works fine but when attempting to show two separate calendars it only displays once. Taking a look at the generated code, it seems that it is naming both calendars the same name - whether I let the package automatically choose the name or even setting the id via setId()...it still chooses the same name for both.

Is there a workaround to this?

**Comment by joaoguilhermels** [comment]
Can you share your code ?

**Comment by joshuand1990** [comment]
for L5.1: calendar you can add something like this.
$calanders [];
$calenders[] = app('laravel-fullcalendar')->addEvents($events)->setOptions($options)->setId($id);

in the view 

foreach($calanders as $calander)
{
  {!!  $calender->calendar() !!}
 {!!  $calender->script() !!}
}

**Comment by maddhatter** [comment]
Need to see the code to try and help with this... if it's still an issue please re-open this.

**Comment by pyesta25** [comment]
Hey I got the same issue here.... I need two calendars with different contents... I tried to put the same code for the other calendar but is displays nothing...

**Comment by Kryptonit3-zz** [comment]
Any updates? How to show 2 calendars with different data on the same page.

**Comment by mrhili** [comment]
How to show 2 calendar ? dont escape :p

**Comment by slowbs** [comment]
still need help about this

**Comment by Pablo-Araya** [comment]
> 
> 
> for L5.1: calendar you can add something like this.
> $calanders [];
> $calenders[] = app('laravel-fullcalendar')->addEvents($events)->setOptions($options)->setId($id);
> 
> in the view
> 
> foreach($calanders as $calander)
> {
> {!! $calender->calendar() !!}
> {!! $calender->script() !!}
> }

Indeed the problem should be due to the id() of each calendar should be different when rendered.
Has anyone tried the code above ?

I'll try to accomplish it and let you guys know !

**Comment by ghost** [comment]
any luck with this? @Pablo-Araya 

you are right this class seems to be a singleton.

**Comment by sunny39** [comment]
did any one try to display multiple calendar on one page if so please tell me
