### ISSUE TITLE
Is it possible to get live calendar?

### ISSUE THREAD

**Issue by roulendz** [maddhatter/laravel-fullcalendar#52]
So the question is if calendar is open by 2 users is it possible that calendar updates.
For example after external event drop, resize or drag.

I was trying with 

```
$('#calendar-schedule').fullCalendar( 'refetchEvents' );
```

and

```
$('#calendar-schedule').fullCalendar( 'refetchEventSources', sources ); 
```

But no luck so far!

Does anyone have suggestion?

I found script and php that works, but no idea how to implement with this repo.

**setCallbacks**

```
            eventDragStop: function (event, jsEvent, ui, view) {
                if (isElemOverDiv()) {
                    var con = confirm('Are you sure to delete this event permanently?');
                    if(con == true) {
                        $.ajax({
                            url: 'process.php',
                            data: 'type=remove&eventid='+event.id,
                            type: 'POST',
                            dataType: 'json',
                            success: function(response){
                                console.log(response);
                                if(response.status == 'success'){
                                    $('#calendar').fullCalendar('removeEvents');
                                    getFreshEvents();
                                }
                            },
                            error: function(e){ 
                                alert('Error processing your request: '+e.responseText);
                            }
                        });
                    }   
                }
            }

    function getFreshEvents(){
        $.ajax({
            url: 'process.php',
            type: 'POST', // Send post data
            data: 'type=fetch',
            async: false,
            success: function(s){
                freshevents = s;
            }
        });
        $('#calendar').fullCalendar('addEventSource', JSON.parse(freshevents));
    }

```

and
**Controller store method**

```
if($type == 'fetch')
{
    $events = array();
    $query = mysqli_query($con, "SELECT * FROM calendar");
    while($fetch = mysqli_fetch_array($query,MYSQLI_ASSOC))
    {
    $e = array();
    $e['id'] = $fetch['id'];
    $e['title'] = $fetch['title'];
    $e['start'] = $fetch['startdate'];
    $e['end'] = $fetch['enddate'];

    $allday = ($fetch['allDay'] == "true") ? true : false;
    $e['allDay'] = $allday;

    array_push($events, $e);
    }
    echo json_encode($events);
}
```

This should work, but how to impliment here?

**Comment by Gummibeer** [comment]
You have to create a Controller method that returns all Events as json and in your JavaScript part you fetch this Route in a given interval and Display these Events.

**Comment by avastamin** [comment]
@Gummibeer is right. I want to add more here: You need to use callback in this case: https://fullcalendar.io/docs/event_rendering/eventRender/
`var myCustomFunction = function(events) {
    // do something
}

var myCustomFetchFunction = function(start, end, callback) {
    $.ajax({
        url: 'feed.php',
        dataType: 'json',
        data: {
            // our hypothetical feed requires UNIX timestamps
            start: Math.round(start.getTime() / 1000),
            end: Math.round(end.getTime() / 1000)
            // additional parameters can be added here
        },
        success: function(events) {
            callback(events);
            // this is where I do some custom stuff with the events
            myCustomFunction(events);
        }
    });
};

$('#calendar').fullCalendar({
     events: myCustomFetchFunction()
});
`
