### ISSUE TITLE
Change event color

### ISSUE THREAD

**Issue by diegorodriguezvidal** [maddhatter/laravel-fullcalendar#54]
Nice package!

How can we change event colors?

**Comment by joaoguilhermels** [comment]
The last parameter of \Calendar::event is an options array where you can set the 'color' of the event for example:

\Calendar::event(
        "Event1", //event title
        false, //full day event?
        $start, //start time (you can also use Carbon instead of DateTime)
        $end, //end time (you can also use Carbon instead of DateTime)
        $id, //optionally, you can specify an event ID
        [
            'color' => '#444444',
            'url' => '#',
            'description' => "Event Description",
            'textColor' => '#0A0A0A'
        ]
);

**Comment by diegorodriguezvidal** [comment]
Thank you, working perfectly!:)

**Comment by mrdavidhsieh** [comment]
I got my code like this; however, I can't make my event change into the color I want. Any help?
`foreach ($travel as $travels) {
    if($travels->verify == "verified"){
      $title = "✔"."[出差(已審核)]"."━"."姓名：".$travels->name."客戶：".$travels->client."事由：".$travels->reason;
      $start_time = $travels->date."T".$this->clean($travels->start_time);
      $end_time = $travels->date."T".$this->clean($travels->end_time);
      $events[] = \Calendar::event(
        $title, //event title
        false, //full day event?
        $start_time, //start time (you can also use Carbon instead of DateTime)
        $end_time, //end time (you can also use Carbon instead of DateTime)
        [
          'color' => '#A20055'
        ]
      );`

**Comment by amsanket22** [comment]
I want the background color for entire cell or date we can say like we show color for the today's date.
