### ISSUE TITLE
Using Laravel 4.2 : can I pass the url and the event color whiten $events array

### ISSUE THREAD

**Issue by johnef** [maddhatter/laravel-fullcalendar#56]
Hi I tried to get all the events from my database using `foreach` 

the `Evant` implement `MaddHatter\LaravelFullcalendar\Event`

```
$eloquentEvent = Evant::all(); //EventModel implements MaddHatter\LaravelFullcalendar\Event
        
        $events = [];
        foreach ($eloquentEvent as $ge) {
            $events[] = Calendar::event(
                $ge->title, //event title
                false, //full day event?
                $ge->start_time, //start time (you can also use Carbon instead of DateTime)
                $ge->end_time //end time (you can also use Carbon instead of DateTime)
            );
        }

        $calendar = Calendar::addEvents($events);

        return View::make('admin.event.view', compact('calendar'));
```

it's working OK, but can't find a way to pass the url and color for each event.
or
can you please suggest me a better way to do this

**Comment by maddhatter** [comment]
if `Evant` implements `MaddHatter\LaravelFullcalendar\Event`, there's no need for that loop.

```php
$eloquentEvents = Evant::all(); //EventModel implements MaddHatter\LaravelFullcalendar\Event
        
       
        $calendar = Calendar::addEvents($eloquentEvents->toArray());

        return View::make('admin.event.view', compact('calendar'));
```

I think if I merge #43, you'll be able to add a `getEventOptions` method to `Evant` that you can use to set the URL, color, etc.

I'll merge and tag that momentarily...

**Comment by maddhatter** [comment]
Tagged v.0.2.2. Try adding that `getEventOptions` method on `Evant` to set extra Fullcalendar options for the event.

**Comment by johnef** [comment]
@maddhatter Thanks sir for the suggest but when I did that and I updated my project with the new [#43](https://github.com/maddhatter/laravel-fullcalendar/pull/43) I got this error 

> Argument 1 passed to MaddHatter\LaravelFullcalendar\EventCollection::push() must implement interface MaddHatter\LaravelFullcalendar\Event, array given, called in C:\....\local\vendor\maddhatter\laravel-fullcalendar\src\MaddHatter\LaravelFullcalendar\Calendar.php on line 158 and defined 

can you please help what's I missing here?

thanks again for the effort

**Comment by maddhatter** [comment]
Make sure you're using `addEvents` (plural) instead of `addEvent` (singular)

**Comment by johnef** [comment]
@maddhatter I am sure that I am using `addEvents`

see here is my controller
```
public function index()
    {
        $eloquentEvents = Evant::all(); //EventModel implements MaddHatter\LaravelFullcalendar\Event
        $calendar = Calendar::addEvents($eloquentEvents->toArray());
        return View::make('admin.event.view', compact('calendar'));
    }
```
and here is my Class

```
class Evant extends Eloquent implements \MaddHatter\LaravelFullcalendar\Event
{
    protected $dates = ['start', 'end'];
    /**
     * Get the event's title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Is it an all day event?
     *
     * @return bool
     */
    public function isAllDay()
    {
        return (bool)$this->all_day;
    }

    /**
     * Get the start time
     *
     * @return DateTime
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * Get the end time
     *
     * @return DateTime
     */
    public function getEnd()
    {
        return $this->end;
    }
}
```
but same error is there!!
