### ISSUE TITLE
Removing events

### ISSUE THREAD

**Issue by shigawaka** [maddhatter/laravel-fullcalendar#61]
How do I call the calendar when I want to remove an event? I am using Ajax.
for example this code:

```
eventClick: function( event, jsEvent, view ) {
$.ajax({
   url: 'calendar/remove_event.php',
   data: 'id=' + event.id,
   type: "POST",
   success: function () {
      $('#calendar').fullCalendar('removeEvents', calEvent._id);
   }
 });
},
```

**Comment by maddhatter** [comment]
Sorry, this is out of the scope of this package. You'll need to write logic to interact with your event model to remove an item.
