### ISSUE TITLE
Events Tooltip

### ISSUE THREAD

**Issue by Sunil-tc** [maddhatter/laravel-fullcalendar#63]
How to show tooltip for the events for eventMouseover event ?

**Comment by maddhatter** [comment]
That seems more like a FullCalendar.io issue, not one with this package.

You'll need to create a callback as [documented on FullCalender.io](https://fullcalendar.io/docs/mouse/eventMouseover/). Then set the callback with `setCallbacks(['eventMouseover' => 'function()....'])` on your calendar. The [sample](https://github.com/maddhatter/laravel-fullcalendar#sample-controller-code) in the readme has a callback example.
