### ISSUE TITLE
How to configure option titleFormat with setOption in FullCalendar for Laravel? 

### ISSUE THREAD

**Issue by felipe-correia** [maddhatter/laravel-fullcalendar#64]
I want to configure titleFormat of fullcalendar but I'm not getting a good result.  The date appears like this {0ona12: 'Janeiro yyyy – 59onp11: 'Janeiro yyyy'}. Here is my code:
```php
public function show(){
    	$events = [];
    	$titleFormat = "{month: 'MMMM yyyy'}";
    	$startTime = '02/01/2017T0900';
    	$endTime = '02/01/2017T1100';

    	$events[] = \Calendar::event(
    		"Event one",
    		false,
    		$startTime,
    		$endTime,
    		0
    	);

    	$calendar = \Calendar::addEvents($events)->setOptions(['first_day' => 1, 
    		'lang' => 'pt-br', 'titleFormat' => $titleFormat])->setCallbacks([]);

    	return view('/calendario', ['calendar' => $calendar]);
    }
```

**Comment by maddhatter** [comment]
Sort of a guess, but I don't think you should be setting `$titleFormat` as a JSON string. Try `$titleFormat = ['month' => 'MMMM yyyy']`.

I'm not sure that'll give you the result you want either though, looks like you want something like [this](https://fullcalendar.io/docs/views/View-Specific-Options/), which would probably be closer to
```php
->setOptions(['views' => [
    'month' => [
        'titleFormat' => 'MMMM yyyy'
    ]
]])
```

(You should consider that block of code psuedo-code, I didn't test it)
