### ISSUE TITLE
How do I make color for each event

### ISSUE THREAD

**Issue by xAl3xFx** [maddhatter/laravel-fullcalendar#66]
Hello, I am wondering if it is possible to have different color for each event in my callendar? Thanks in advance :100:

**Comment by maddhatter** [comment]
You can figure out what parameters you'd need to set for the event from fullcalendar.io, and set it using one of the methods described here https://github.com/maddhatter/laravel-fullcalendar#additional-event-parameters

**Comment by xAl3xFx** [comment]
Thank you :+1:
