### ISSUE TITLE
Calendar not showing

### ISSUE THREAD

**Issue by KSVQ** [maddhatter/laravel-fullcalendar#70]
I get this in view when I try to output the calendar by following the example. Laravel 5.4

`<div id="calendar-zmx8pav5"></div> <script> $(document).ready(function(){ $('#calendar-zmx8pav5').fullCalendar({"header":{"left":"prev,next today","center":"title","right":"month,agendaWeek,agendaDay"},"eventLimit":true,"firstDay":1,"viewRender":function() {alert("Callbacks!");},"events":[{"id":0,"title":"Event One","allDay":false,"start":"2015-02-11T08:00:00+00:00","end":"2015-02-12T08:00:00+00:00","color":"#800"},{"id":"stringEventId","title":"Valentine's Day","allDay":true,"start":"2015-02-14T00:00:00+00:00","end":"2015-02-14T00:00:00+00:00","color":"#800"}]}); }); </script> `

**Comment by maddhatter** [comment]
Make sure you include the FullCalendar scripts before doing `{{ $calendar->script() }}`. You'll need their .js files and .css files.

There's an example here: https://github.com/maddhatter/laravel-fullcalendar#sample-view
