### ISSUE TITLE
how can i add Description in event

### ISSUE THREAD

**Issue by vikashswami** [maddhatter/laravel-fullcalendar#84]
hi, 
 i'm new in laravel & i don't know much about it 
i want to use description in event. can anybody help me how to configure it.
my controller
 for($i=0;$i<$length;$i++)
			{
				$name      =$CalTable[$i]->name;
				$body      =$CalTable[$i]->body;// NOT Working Now
	            $full_day  =$CalTable[$i]->full_day;
	            $sdatetime =$CalTable[$i]->sdatetime;
	            $edatetime =$CalTable[$i]->edatetime;
	            $eventid   =$CalTable[$i]->eventid;
	            $ecolor    =$CalTable[$i]->ecolor;
				$textColor =$CalTable[$i]->textcolor;
				$URLlink   =$CalTable[$i]->url;
				$events[] = \Calendar::event(
				            $name,
							$full_day,
							$sdatetime,
							$edatetime,
							$eventid,
							[
							'color'=>$ecolor,
							//'backgroundColor'=>$bgcolors,
							'textColor'=>$textColor,
							//'borderColor'=>$bgcolors,	
                                                       //'rendering'=>'background',
							'description' => $CalTable[$i]-> body,
							'url' => $URLlink,										
							]
							);	
			}

*** View ***
<body>
View Section
    {!! $calendar->calendar() !!}
    {!! $calendar->script() !!}	
</body>

it display only event title not description.
and how description show

**Comment by coryrose1** [comment]
I would like to know this as well.

I'm able to add the description field in the event parameters.

// Events array
            $events[] = Calendar::event(
                $event->title, //event title
                false, //full day event?
                $event->start, //start time (you can also use Carbon instead of DateTime)
                $event->end, //end time (you can also use Carbon instead of DateTime)
                $event->id,
                [
                    'url' => $url,
                    'color' => $color,
                    'textColor' => $textColor,
                    'description' => $description,
                ]
            );

Since we're just using the blade shortcuts to render the calendar and not using the JS itself where we can call eventRender:

 eventRender: function(event, element) {
        element.qtip({
            content: event.description
        });
    }

How do we append the description to the event on the calendar in the view?
